name: Run PyTest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run PyTest
        run: |
          pytest -v tests/ | tee pytest-log.txt

      - name: Upload test logs
        if: always()   # même si les tests échouent, on garde les logs
        uses: actions/upload-artifact@v3
        with:
          name: pytest-logs
          path: pytest-log.txt
