name: PyTest Report

on:
  push:
    branches: [main]

jobs:
  pytest-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements-ci.txt

      - name: Run tests with HTML report
        run: pytest tests --maxfail=1 --disable-warnings -q --html=monitoring/reports/pytest_report.html --self-contained-html

      - name: Upload pytest report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: monitoring/reports/pytest_report.html
