name: Run PyTest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   # ← passe à v4

      - name: Setup Python
        uses: actions/setup-python@v5   # ← passe à v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run PyTest
        run: pytest -v tests/

